# --------------------------------------------------------------------------------------------------
# CloudFormation Network Layer: VPC, Subnets + RouteTables, Internet
# Author: Andrei Rohau
#
# Version      Date           Name                Info
# 1.0          12-05-2021    Andrei Rohau       Initial Version
#
# --------------------------------------------------------------------------------------------------
AWSTemplateFormatVersion: 2010-09-09
Description: "Network: VPC, Subnets + RouteTables, Internet"

Metadata:
 AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration (My Ip 37.214.27.94/32)"
        Parameters: 
          - Environment
          - MyOwnSgDb
          - MyOwnSgCommon
          - MyOwnSg
          - MyOwnSn
          - MyOwnEC2IamInstanceProfile
          - MyOwnAmiId
          - MyOwnKeyName
          - EC2InstanceType
          - MyOwnUserDataValueBase64Encoded
          - MyOwnPostfix
      - 
        Label: 
          default: "Availability Zones"
        Parameters: 
          - AvailabilityZone

Parameters:
  Environment:
    Type: String
    Default: "DEV"

  MyOwnSgDb:
    Type: String
    Default: '' # My default security group 3306
    
  MyOwnSg:
    Type: String
    Default: '' # My default security group 22(ip), 80, 8080

  MyOwnSn:
    Type: String
    Default: '' # AWS default subnet

  MyOwnEC2IamInstanceProfile:
    Type: String
    Default: 'FullAccessRoleEC2AndS3AndRds'

  MyOwnAmiId:
    Type: String
    Default: 'ami-0d5eff06f840b45e9'

  MyOwnKeyName:
    Type: String
    Default: ''

  EC2InstanceType:
    Type: String
    Default: 't2.micro'

  MyOwnUserDataValueBase64Encoded:
    Type: String
    Default: ''

  AvailabilityZone:
    Type: String
    Default: 'us-east-1a'
    
  MyOwnPostfix:
    Type: String
    Default: 'v-'

Resources:

#====== EC2 ======
  MyOwnEC2: 
    Type: AWS::EC2::Instance
    Properties: 
      IamInstanceProfile: !Ref MyOwnEC2IamInstanceProfile
      ImageId: !Ref MyOwnAmiId
      KeyName: !Ref MyOwnKeyName
      InstanceType: !Ref EC2InstanceType
      SecurityGroupIds:
      - !Ref MyOwnSgDb
      - !Ref MyOwnSgCommon
      - !Ref MyOwnSg
      SubnetId: !Ref MyOwnSn
      AvailabilityZone: !Ref AvailabilityZone
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "8"
      DisableApiTermination: "false"
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            - - ''
              - !Ref MyOwnUserDataValueBase64Encoded
      Tags: 
      - Key: "Name"
        Value: !Join [ "-", [ !Ref Environment, "MyOwnEC2", !Ref MyOwnPostfix ] ]
            
            
            
            
            
            
            
            
            